<?php

namespace AppBundle\Repository;

/**
 * EventSignupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventSignupRepository extends \Doctrine\ORM\EntityRepository
{
}
