<?php

namespace AppBundle\Repository;

/**
 * WowCharacterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WowCharacterRepository extends \Doctrine\ORM\EntityRepository
{
}
