AppBundle\Entity\Quote:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\QuoteRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        content:
            type: string
            length: '1024'
        user:
            type: string
            length: '1024'
        createdAt:
            type: datetime
            column: created_at
    lifecycleCallbacks: {  }
